package lkd.namsic.game.enums;

public enum LogData {

    BUY,
    SELL,
    BUFF_RECEIVE,
    CHAT,
    DEATH,
    ADVENTURE,
    FIELD_MOVE_DISTANCE,
    FIGHT,
    FISH,
    GATHER,
    LOG_COUNT,
    MAP_MOVE_DISTANCE,
    MAX_CLOSERATE,
    MAX_MONEY,
    MAX_PAYMENT,
    MINED,
    PLAYED_DAY,
    QUEST_CLEAR,
    QUEST_RECEIVE,
    REINFORCE_SUCCESS,
    REINFORCE_TRY,
    TOTAL_CLOSERATE,
    TOTAL_EXP,
    TOTAL_EQUIP_USE,
    TOTAL_ITEM_USE,
    TOTAL_ITEM_EAT,
    TOTAL_MONEY

}
