package lkd.namsic.game.enums;

public enum Variable {

    IS_TUTORIAL,
    HIGH_PRIORITY_ITEM,
    MINE,
    FISH,
    FISH_WAIT_TYPE,
    FISH_MAP,
    FISH_SKILL,
    IS_TURN,
    FIGHT_WAIT_TYPE,
    FIGHT_ITEM_ID,
    FIGHT_USED_ITEM,
    FIGHT_TARGET_MAX_INDEX,
    FIGHT_TARGET_INDEX,
    IS_DEFENCING,
    IS_FIGHT_RESPONSE,
    ADVENTURE_FIGHT,
    ADVENTURE_WAIT_TYPE,
    IS_APPRAISE_STOP,
    GHOST_SWORD_1,

}
