package lkd.namsic.game.enums;

public enum Variable {

    IS_TUTORIAL,
    HIGH_PRIORITY_ITEM,
    MINE,
    FISH,
    FISH_WAIT_TYPE,
    FISH_MAP,
    FISH_SKILL,
    IS_TURN,
    FIGHT_WAIT_TYPE,
    FIGHT_ITEM_ID,
    FIGHT_USED_ITEM,
    FIGHT_TARGET_MAX_INDEX,
    FIGHT_TARGET_INDEX,
    IS_DEFENCING,
    IS_FIGHT_RESPONSE,
    ADVENTURE_FIGHT,
    ADVENTURE_WAIT_TYPE,
    IS_APPRAISE_STOP,
    SHOP,
    SHOP_ITEM_ID,
    SHOP_ITEM_COUNT,
    SHOP_PAGE,
    GHOST_SWORD_1,
    SLIME_CHESTPLATE,
    SLIME_CHESTPLATE_USE,
    WEIRD_LEGGINGS,
    TROLL_CLUB,
    ENT_WAIT_TURN,

}
