 package lkd.namsic.game;

import com.google.common.collect.BiMap;
import com.google.common.collect.ImmutableBiMap;

public class ObjectList {

    public static final BiMap<String, Long> itemList = new ImmutableBiMap.Builder<String, Long>()
            .put("돌멩이", 1L)
            .put("나뭇가지", 2L)
            .put("나뭇잎", 3L)
            .put("잡초", 4L)
            .put("골드 주머니", 5L)
            .put("골드 보따리", 6L)
            .put("약초", 7L)
            .put("마나 조각", 8L)
            .put("흙", 10L)
            .put("모래", 11L)
            .put("유리", 12L)
            .put("유리병", 13L)

            .put("하급 체력 포션", 14L)
            .put("중급 체력 포션", 15L)
            .put("상급 체력 포션", 16L)
            .put("하급 마나 포션", 17L)
            .put("중급 마나 포션", 18L)
            .put("상급 마나 포션", 19L)

            .put("돌", 20L)
            .put("석탄", 21L)
            .put("석영", 22L)
            .put("구리", 23L)
            .put("납", 24L)
            .put("주석", 25L)
            .put("니켈", 26L)
            .put("철", 27L)
            .put("리튬", 28L)
            .put("청금석", 29L)
            .put("레드스톤", 30L)
            .put("은", 31L)
            .put("금", 32L)
            .put("발광석", 33L)
            .put("화염 석영", 34L)
            .put("암흑 석영", 35L)
            .put("명청석", 36L)
            .put("명적석", 37L)
            .put("백금", 38L)
            .put("무연탄", 39L)
            .put("티타늄", 40L)
            .put("투명석", 41L)
            .put("다이아몬드", 42L)
            .put("오리하르콘", 43L)
            .put("적청석", 44L)
            .put("랜디움", 45L)
            .put("에이튬", 46L)

            .put("가넷", 47L)
            .put("자수정", 48L)
            .put("아쿠아마린", 49L)
            .put("에메랄드", 50L)
            .put("진주", 51L)
            .put("루비", 52L)
            .put("페리도트", 53L)
            .put("사파이어", 54L)
            .put("오팔", 55L)
            .put("토파즈", 56L)
            .put("터키석", 57L)

            .put("쓰레기", 58L)
            .put("물풀", 59L)
            .put("(일반) 금강모치", 60L)
            .put("(일반) 미꾸라지", 61L)
            .put("(일반) 붕어", 62L)
            .put("(일반) 송사리", 63L)
            .put("(일반) 피라미", 64L)
            .put("(희귀) 망둑어", 65L)
            .put("(희귀) 미꾸라지", 66L)
            .put("(희귀) 배스", 67L)
            .put("(희귀) 살치", 68L)
            .put("(희귀) 쏘가리", 69L)
            .put("(희귀) 은어", 70L)
            .put("(특별) 강준치", 71L)
            .put("(특별) 망둑어", 72L)
            .put("(특별) 메기", 73L)
            .put("(특별) 뱀장어", 74L)
            .put("(특별) 산천어", 75L)
            .put("(특별) 숭어", 76L)
            .put("(특별) 쏘가리", 77L)
            .put("(특별) 연어", 78L)
            .put("(특별) 은어", 79L)
            .put("(특별) 잉어", 80L)
            .put("(유일) 강준치", 81L)
            .put("(유일) 메기", 82L)
            .put("(유일) 뱀장어", 83L)
            .put("(유일) 산천어", 84L)
            .put("(유일) 숭어", 85L)
            .put("(유일) 연어", 86L)
            .put("(유일) 잉어", 87L)
            .put("(전설) 다금바리", 88L)
            .put("(전설) 돗돔", 89L)
            .put("(전설) 자치", 90L)
            .put("(전설) 쿠니마스", 91L)
            .put("(신화) 실러캔스", 92L)
            .put("(신화) 폐어", 93L)

            .put("전투 비활성화권(1일)", 94L)
            .put("전투 비활성화권(7일)", 95L)

            .put("스텟 포인트", 96L)
            .put("모험 스텟", 97L)
            .put("하급 제작법", 98L)
            .put("중급 제작법", 99L)
            .put("상급 제작법", 100L)
            .put("붉은색 구체", 101L)
            .put("녹색 구체", 102L)
            .put("연녹색 구체", 103L)
            .put("파란색 구체", 104L)
            .put("갈색 구체", 105L)
            .put("회색 구체", 106L)
            .put("은색 구체", 107L)
            .put("연회색 구체", 108L)
            .put("노란색 구체", 109L)
            .put("검은색 구체", 110L)
            .put("흰색 구체", 111L)
            .put("하급 경험치 포션", 112L)
            .put("중급 경험치 포션", 113L)
            .put("상급 경험치 포션", 114L)
            .put("하급 모험의 증표", 115L)
            .put("중급 모험의 증표", 116L)
            .put("상급 모험의 증표", 117L)
            .put("무색의 구체", 118L)

            .put("하급 강화석", 119L)
            .put("중급 강화석", 120L)
            .put("상급 강화석", 121L)

            .put("하급 부적", 122L)
            .put("중급 부적", 123L)
            .put("상급 부적", 124L)

            .put("보석 조각", 125L)
            .put("보석 연마제", 126L)
            .put("빛나는 보석 연마제", 127L)

            .put("무기 완화제", 128L)
 
            .build();

    public final static BiMap<String, Long> equipList = new ImmutableBiMap.Builder<String, Long>()
            .build();

    public final static BiMap<String, Long> monsterList = new ImmutableBiMap.Builder<String, Long>()
            .put("양", 1L)
            .build();

    public final static BiMap<String, Long> bossList = new ImmutableBiMap.Builder<String, Long>()
            .build();

    public final static BiMap<String, Long> questList = new ImmutableBiMap.Builder<String, Long>()
            .put("광부의 일", 1L)
            .put("쓰레기 수거", 2L)
            .put("불이 필요해!", 3L)
            .put("불이 너무 강했나...?", 4L)
            .build();

    public final static BiMap<String, Long> npcList = new ImmutableBiMap.Builder<String, Long>()
            .put("???", 1L)
            .put("아벨", 2L)
            .put("노아", 3L)
            .build();

    public final static BiMap<String, String> mapList = new ImmutableBiMap.Builder<String, String>()
            .put("0-0", "시작의 마을")
            .put("0-1", "조용한 바닷가")
            .put("1-0", "모험의 평원")
            .put("1-1", "평화로운 강")
            .build();

}
